<a href="https://colab.research.google.com/github/TanyaKudaisya/SteedStats/blob/main/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import sklearn.preprocessing as preprocessing
import sklearn.model_selection as model_selection
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

from sklearn import metrics
from sklearn.model_selection import cross_val_score
from sklearn import linear_model
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import VotingRegressor

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("gdaley/hkracing")

print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/gdaley/hkracing?dataset_version_number=2...

100%|██████████| 3.42M/3.42M [00:00<00:00, 105MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/gdaley/hkracing/versions/2

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("gdaley/hkracing")

print("Path to dataset files:", path)

Path to dataset files: /root/.cache/kagglehub/datasets/gdaley/hkracing/versions/2

In [ ]:
# Load the CSV files in Colab
races_df = pd.read_csv('/root/.cache/kagglehub/datasets/gdaley/hkracing/versions/2/races.csv', delimiter=",", header=0, index_col='race_id')
runs_df = pd.read_csv('/root/.cache/kagglehub/datasets/gdaley/hkracing/versions/2/runs.csv', delimiter=",", header=0)

In [ ]:
races_df.shape

(6349, 36)

In [ ]:
runs_df.shape

(79447, 37)

In [ ]:
#useful code to see all the features of my database

pd.set_option('display.max_columns', None)

In [ ]:
df=runs_df

In [ ]:
df=df.drop('won',axis=1)
df=df.drop('lengths_behind',axis=1)
df=df.drop('horse_rating',axis=1)
df=df.drop('horse_gear',axis=1)
df=df.drop('draw',axis=1)
df=df.drop('position_sec1',axis=1)
df=df.drop('position_sec2',axis=1)
df=df.drop('position_sec3',axis=1)
df=df.drop('position_sec4',axis=1)
df=df.drop('position_sec5',axis=1)
df=df.drop('position_sec6',axis=1)
df=df.drop('behind_sec1',axis=1)
df=df.drop('behind_sec2',axis=1)
df=df.drop('behind_sec3',axis=1)
df=df.drop('behind_sec4',axis=1)
df=df.drop('behind_sec5',axis=1)
df=df.drop('behind_sec6',axis=1)
df=df.drop('time1',axis=1)
df=df.drop('time2',axis=1)
df=df.drop('time3',axis=1)
df=df.drop('time4',axis=1)
df=df.drop('time5',axis=1)
df=df.drop('time6',axis=1)
df=df.drop('win_odds',axis=1)
df=df.drop('place_odds',axis=1)

In [ ]:
races_df.head(1)

,date,venue,race_no,config,surface,distance,going,horse_ratings,prize,race_class,sec_time1,sec_time2,sec_time3,sec_time4,sec_time5,sec_time6,sec_time7,time1,time2,time3,time4,time5,time6,time7,place_combination1,place_combination2,place_combination3,place_combination4,place_dividend1,place_dividend2,place_dividend3,place_dividend4,win_combination1,win_dividend1,win_combination2,win_dividend2
race_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,1997-06-02,ST,1,A,0,1400,GOOD TO FIRM,40-15,485000.0,5,13.53,21.59,23.94,23.58,NaN,NaN,NaN,13.53,35.12,59.06,82.64,NaN,NaN,NaN,8,11,6.0,NaN,36.5,25.5,18.0,NaN,8,121.0,NaN,NaN

In [ ]:
runs_df.columns

Index(['race_id', 'horse_no', 'horse_id', 'result', 'won', 'lengths_behind',
       'horse_age', 'horse_country', 'horse_type', 'horse_rating',
       'horse_gear', 'declared_weight', 'actual_weight', 'draw',
       'position_sec1', 'position_sec2', 'position_sec3', 'position_sec4',
       'position_sec5', 'position_sec6', 'behind_sec1', 'behind_sec2',
       'behind_sec3', 'behind_sec4', 'behind_sec5', 'behind_sec6', 'time1',
       'time2', 'time3', 'time4', 'time5', 'time6', 'finish_time', 'win_odds',
       'place_odds', 'trainer_id', 'jockey_id'],
      dtype='object')

In [ ]:
df = pd.merge(df,races_df[['venue','config','surface','distance','going']],on='race_id', how='left')

In [ ]:
#I didn't add "race_no" because if the ground gets damaged during the races I know it from the 'going' variable.

#I didn't add "date" because I know the horse age.

#Including 'id's as a feature will not make sense at all, because the model will treat the id as a numeric value which will decrease the model performance.

#Analyzing the previous db I replace the 'horse_id', 'jockey_id' and 'trainer_id' with the percentage of podiums wons.

runs_df.head(3)

,race_id,horse_no,horse_id,result,won,lengths_behind,horse_age,horse_country,horse_type,horse_rating,horse_gear,declared_weight,actual_weight,draw,position_sec1,position_sec2,position_sec3,position_sec4,position_sec5,position_sec6,behind_sec1,behind_sec2,behind_sec3,behind_sec4,behind_sec5,behind_sec6,time1,time2,time3,time4,time5,time6,finish_time,win_odds,place_odds,trainer_id,jockey_id
0,0,1,3917,10,0.0,8.00,3,AUS,Gelding,60,--,1020.0,133,7,6,4,6,10.0,NaN,NaN,2.0,2.0,1.50,8.00,NaN,NaN,13.85,21.59,23.86,24.62,NaN,NaN,83.92,9.7,3.7,118,2
1,0,2,2157,8,0.0,5.75,3,NZ,Gelding,60,--,980.0,133,12,12,13,13,8.0,NaN,NaN,6.5,9.0,5.00,5.75,NaN,NaN,14.57,21.99,23.30,23.70,NaN,NaN,83.56,16.0,4.9,164,57
2,0,3,858,7,0.0,4.75,3,NZ,Gelding,60,--,1082.0,132,8,3,2,2,7.0,NaN,NaN,1.0,1.0,0.75,4.75,NaN,NaN,13.69,21.59,23.90,24.22,NaN,NaN,83.40,3.5,1.5,137,18

In [ ]:
#new horse features
horse_tot_race=runs_df.groupby(['horse_id'])['result'].apply(lambda x: (x).sum()).reset_index(name='horse_tot_race')

In [ ]:
df=pd.merge(df,horse_tot_race,on='horse_id',how='left')

In [ ]:
horse_tot_place=runs_df.groupby(['horse_id'])['result'].apply(lambda x: (x <=3).sum()).reset_index(name='horse_tot_place')

In [ ]:
df=pd.merge(df,horse_tot_place,on='horse_id',how='left')

In [ ]:
#New jockey features
jockey_tot_race=runs_df.groupby(['jockey_id'])['result'].apply(lambda x: (x).sum()).reset_index(name='jockey_tot_race')

In [ ]:
df=pd.merge(df,jockey_tot_race,on='jockey_id',how='left')

In [ ]:
jockey_tot_place=runs_df.groupby(['jockey_id'])['result'].apply(lambda x: (x <=3).sum()).reset_index(name='jockey_tot_place')

In [ ]:
df=pd.merge(df,jockey_tot_place,on='jockey_id',how='left')

In [ ]:
#New trainer features

trainer_tot_race=runs_df.groupby(['trainer_id'])['result'].apply(lambda x: (x).sum()).reset_index(name='trainer_tot_race')

In [ ]:
  df=pd.merge(df,trainer_tot_race,on='trainer_id',how='left')

In [ ]:
trainer_tot_place=runs_df.groupby(['trainer_id'])['result'].apply(lambda x: (x <=3).sum()).reset_index(name='trainer_tot_place')

In [ ]:
df=pd.merge(df,trainer_tot_place,on='trainer_id',how='left')

In [ ]:
#Now that we have the new data, we can create the new columns with the victory and placement percentages of the jockeys and coaches.

#new horse features
df['horse_place_perc']=df['horse_tot_place']/df['horse_tot_race']

#new jockey features
df['jockey_place_perc']=df['jockey_tot_place']/df['jockey_tot_race']

#new trainer features
df['trainer_place_perc']=df['trainer_tot_place']/df['trainer_tot_race']

In [ ]:
#We delete the columns that we no longer need.
df.columns

Index(['race_id', 'horse_no', 'horse_id', 'result', 'horse_age',
       'horse_country', 'horse_type', 'declared_weight', 'actual_weight',
       'finish_time', 'trainer_id', 'jockey_id', 'venue', 'config', 'surface',
       'distance', 'going', 'horse_tot_race', 'horse_tot_place',
       'jockey_tot_race', 'jockey_tot_place', 'trainer_tot_race',
       'trainer_tot_place', 'horse_place_perc', 'jockey_place_perc',
       'trainer_place_perc'],
      dtype='object')

In [ ]:
df=df.drop('horse_tot_place',axis=1)
df=df.drop('horse_tot_race',axis=1)
df=df.drop('horse_id',axis=1)


df=df.drop('trainer_tot_place',axis=1)
df=df.drop('trainer_tot_race',axis=1)
df=df.drop('trainer_id',axis=1)


df=df.drop('jockey_tot_place',axis=1)
df=df.drop('jockey_tot_race',axis=1)
df=df.drop('jockey_id',axis=1)

In [ ]:
#The database is used to create an algorithm that predicts the time of the race, so we also delete: 'horse_no'. no race_id because we need for the machine learning test.

df=df.drop('horse_no',axis=1)

In [ ]:
#DATA CLEANING
#I set the variables in alphabetical order and "finish_time"(Y) to the first

df = df.sort_index(axis=1, ascending=True)

In [ ]:
temp_cols=df.columns.tolist()
index=df.columns.get_loc("finish_time")
new_cols=temp_cols[index:index+1] + temp_cols[0:index] + temp_cols[index+1:]
df=df[new_cols]

In [ ]:
df.shape

(79447, 16)

In [ ]:
df.head(2)

,finish_time,actual_weight,config,declared_weight,distance,going,horse_age,horse_country,horse_place_perc,horse_type,jockey_place_perc,race_id,result,surface,trainer_place_perc,venue
0,83.92,133,A,1020.0,1400,GOOD TO FIRM,3,AUS,0.026432,Gelding,0.073136,0,10,0,0.063716,ST
1,83.56,133,A,980.0,1400,GOOD TO FIRM,3,NZ,0.023622,Gelding,0.042150,0,8,0,0.036792,ST

In [ ]:
#Na values were 2. I drop NA.

#df.isna().sum()

df=df.dropna()

In [ ]:
#Let's correct the dtypes and encode our columns

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 79445 entries, 0 to 79446
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   finish_time         79445 non-null  float64
 1   actual_weight       79445 non-null  int64
 2   config              79445 non-null  object
 3   declared_weight     79445 non-null  float64
 4   distance            79445 non-null  int64
 5   going               79445 non-null  object
 6   horse_age           79445 non-null  int64
 7   horse_country       79445 non-null  object
 8   horse_place_perc    79445 non-null  float64
 9   horse_type          79445 non-null  object
 10  jockey_place_perc   79445 non-null  float64
 11  race_id             79445 non-null  int64
 12  result              79445 non-null  int64
 13  surface             79445 non-null  int64
 14  trainer_place_perc  79445 non-null  float64
 15  venue               79445 non-null  object
dtypes: float64(5), int64(6), object(5)
memory usage: 10.3+ MB

In [ ]:
# encode ordinal columns: config,going
config_encoder = preprocessing.OrdinalEncoder()
df['config'] = config_encoder.fit_transform(df['config'].values.reshape(-1, 1))

going_encoder = preprocessing.OrdinalEncoder()
df['going'] = going_encoder.fit_transform(df['going'].values.reshape(-1, 1))

In [ ]:
# encode nominal column: venue, horse_country, horse_type
venue_encoder = preprocessing.LabelEncoder()
df['venue'] = venue_encoder.fit_transform(df['venue'])

horse_country_encoder = preprocessing.LabelEncoder()
df['horse_country'] = horse_country_encoder.fit_transform(df['horse_country'])

horse_type_encoder = preprocessing.LabelEncoder()
df['horse_type'] = horse_type_encoder.fit_transform(df['horse_type'])

In [ ]:
df.head(3)

,finish_time,actual_weight,config,declared_weight,distance,going,horse_age,horse_country,horse_place_perc,horse_type,jockey_place_perc,race_id,result,surface,trainer_place_perc,venue
0,83.92,133,0.0,1020.0,1400,2.0,3,1,0.026432,3,0.073136,0,10,0,0.063716,1
1,83.56,133,0.0,980.0,1400,2.0,3,11,0.023622,3,0.042150,0,8,0,0.036792,1
2,83.40,132,0.0,1082.0,1400,2.0,3,11,0.024000,3,0.059514,0,7,0,0.041787,1

In [ ]:
df.shape

(79445, 16)

In [ ]:
corr = df.corr()
corr.style.background_gradient(cmap='coolwarm').format(precision=2)

In [ ]:
#ML
#As you can see from the database we have kept the columns "result" and "race_id" which are not useful for machine learning.

#These columns will serve us to create 2 new databases to test our algorithm on a particular ride.

#1st database with race_id=0 , 2nd race_id=3
df_0=df[df.race_id==0]
df_3=df[df.race_id==3]

In [ ]:
df_0.shape

(14, 16)

In [ ]:
df_3.shape

(12, 16)

In [ ]:
df.shape

(79445, 16)

In [ ]:
df=df[df.race_id!=0]

In [ ]:
df=df[df.race_id!=3]

In [ ]:
df.shape

(79419, 16)

In [ ]:
#now I can drop race_id and result
df=df.drop('race_id',axis=1)
df=df.drop('result',axis=1)

df_0_ML=df_0
df_0_ML=df_0_ML.drop('race_id',axis=1)
df_0_ML=df_0_ML.drop('result',axis=1)

df_3_ML=df_3
df_3_ML=df_3_ML.drop('race_id',axis=1)
df_3_ML=df_3_ML.drop('result',axis=1)

In [ ]:
#The features are not in the same scale, we have to standardize the variables in the X dataset.
#STANDARDIZATION

X = df[df.columns[1:]]
ss = preprocessing.StandardScaler()
X = pd.DataFrame(ss.fit_transform(X),columns = X.columns)

In [ ]:
y_time = df.finish_time

In [ ]:
#We are not going to use those db now
X_0= df_0_ML[df_0_ML.columns[1:]]
ss = preprocessing.StandardScaler()
X_0= pd.DataFrame(ss.fit_transform(X_0),columns = X_0.columns)

In [ ]:
X_3 = df_3_ML[df_3_ML.columns[1:]]
ss = preprocessing.StandardScaler()
X_3 = pd.DataFrame(ss.fit_transform(X_3),columns = X_3.columns)

In [ ]:
#Split in train (75%) and test (25%) sets

# split data into train and test sets
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y_time, train_size=0.75, test_size=0.25, random_state=1)

In [ ]:
print('X_train', X_train.shape)
print('y_train', y_train.shape)
print('X_test', X_test.shape)
print('y_test', y_test.shape)

X_train (59564, 13)
y_train (59564,)
X_test (19855, 13)
y_test (19855,)

In [ ]:
#Cross Validation Models

lr= linear_model.LinearRegression()
cv= cross_val_score(lr,X_train,y_train,cv=5)
print(cv)
print(cv.mean())

[0.99588152 0.99616841 0.99626049 0.99580449 0.99591879]
0.9960067420381294

In [ ]:
knn= KNeighborsRegressor(n_neighbors=4)
cv= cross_val_score(knn,X_train,y_train,cv=5)
print(cv)
print(cv.mean())

[0.94698575 0.94766055 0.94680707 0.94617234 0.94792369]
0.9471098800810335

In [ ]:
tree=DecisionTreeRegressor(random_state=1)
cv= cross_val_score(tree,X_train,y_train,cv=5)
print(cv)
print(cv.mean())

[0.99377599 0.99421119 0.99400205 0.99366852 0.99425763]
0.9939830754283765

In [ ]:
rf=RandomForestRegressor(random_state=1)
cv= cross_val_score(rf,X_train,y_train,cv=5)
print(cv)
print(cv.mean())

[0.99685188 0.99705482 0.99703044 0.99663364 0.9968879 ]
0.9968917336989689

In [ ]:
#VotingRegressor
voting_rg=VotingRegressor(estimators=[('lr',lr),('rf',rf)])
cv= cross_val_score(voting_rg,X_train,y_train,cv=5)
print(cv)
print(cv.mean())

[0.99673688 0.99698196 0.99701893 0.99658267 0.99676498]
0.9968170841120753

In [ ]:
#PREDICTIONS
#linear regression
lr.fit(X_train,y_train)
y_lr=lr.predict(X_test)

In [ ]:
print("Linear Regression results:")
print("R^2",metrics.r2_score(y_test,y_lr))
print("Mean Absolute Error", metrics.mean_absolute_error(y_test,y_lr))
print("Mean Squared Error", metrics.mean_squared_error(y_test,y_lr))
print("Root Mean Squared Error",np.square(metrics.mean_squared_error(y_test,y_lr)))

Linear Regression results:
R^2 0.9946792582139028
Mean Absolute Error 0.8359192881085424
Mean Squared Error 1.8226781745948542
Root Mean Squared Error 3.3221557281444296

In [ ]:
#Random Forest
rf.fit(X_train,y_train)
y_rf=rf.predict(X_test)

In [ ]:
print("Random Forest results:")
print("R^2",metrics.r2_score(y_test,y_rf))
print("Mean Absolute Error", metrics.mean_absolute_error(y_test,y_rf))
print("Mean Squared Error", metrics.mean_squared_error(y_test,y_rf))
print("Root Mean Squared Error",np.square(metrics.mean_squared_error(y_test,y_rf)))

Random Forest results:
R^2 0.9956045608333481
Mean Absolute Error 0.7088320771146364
Mean Squared Error 1.5057056626482632
Root Mean Squared Error 2.2671495425310453

In [ ]:
#VotingRegressor
voting_rg.fit(X_train,y_train)
y_voting_rg=voting_rg.predict(X_test)

In [ ]:
print("Voting Regressor results:")
print("R^2",metrics.r2_score(y_test,y_voting_rg))
print("Mean Absolute Error", metrics.mean_absolute_error(y_test,y_voting_rg))
print("Mean Squared Error", metrics.mean_squared_error(y_test,y_voting_rg))
print("Root Mean Squared Error",np.square(metrics.mean_squared_error(y_test,y_voting_rg)))

Voting Regressor results:
R^2 0.9954981078532233
Mean Absolute Error 0.7298832822651027
Mean Squared Error 1.5421722929217023
Root Mean Squared Error 2.3782953810553806

In [ ]:
#Analyzing the MSE and MAE the best is the Random Forest,than Voting Regressor and third Linear Regression

#CONCLUSION TEST

#We try to predict the time to each horse and understand who is the winner using our algoritm in the race_id= 0 and race_id= 3

df_0['pred']=voting_rg.predict(X_0)

In [ ]:
df_0 = df_0[['finish_time','pred','result']]

In [ ]:
df_0['result_pred'] = df_0['pred'].rank(ascending=True).astype(int)

In [ ]:
df_0

    finish_time       pred  result  result_pred
0         83.92  84.099952      10            3
1         83.56  84.559753       8           10
2         83.40  84.158358       7            4
3         83.62  84.432091       9            9
4         83.24  84.413572       6            8
5         82.83  84.412388       3            7
6         84.15  84.782429      12           12
7         82.64  84.064142       1            2
8         84.20  84.334707      13            6
9         92.20  85.232754      14           14
10        82.77  83.648311       2            1
11        82.98  84.634949       4           11
12        83.94  84.260303      11            5
13        83.08  84.849059       5           13

In [ ]:
#We see that the algorithm has guessed 2 horses out of 3 placed.

#Now we use the last db

df_3['pred']=voting_rg.predict(X_3)

In [ ]:
df_3 = df_3[['finish_time','pred','result']]

In [ ]:
df_3['result_pred'] = df_3['pred'].rank(ascending=True).astype(int)

In [ ]:
df_3

    finish_time       pred  result  result_pred
42        69.23  84.693848       5            8
43        69.34  84.559537       6            7
44        69.16  84.066050       2            2
45        70.22  84.407887      11            6
46        68.89  83.114611       1            1
47        69.75  84.777031      10           11
48        69.22  84.730205       4           10
49        69.57  84.140775       7            3
50        69.67  84.894148       9           12
51        69.20  84.165385       3            4
52        69.66  84.323102       8            5
53        70.52  84.694865      12            9